name: Find Your Marc
favicon: null
layout_spectrum: 0.9465459478087723
typography_spectrum: 0.0719598161522299
title: Find Your Marc - Documenting as much of the World as Possible
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f4d50'
    - '#ada49e'
    - '#060606'
    - '#f3f9fe'
    - '#90705e'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
